apiVersion: extensions/v1beta1
kind: Deployment
metadata:
        name: testing-deployment
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: jenkinstesting
        template:
                metadata:
                        labels:
                                app: jenkinstesting
                spec:
                        containers:
                                 - name: jenkinstesting-container
                                   image: jakkrit0660/jackjenline:16
                                   ports: 
                                   - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
        name: service-jenkinstesting
spec:
        selector:
                app: jenkinstesting
        type: NodePort
        ports:
                - port: 8000
                  targetPort: 80 
                  nodePort: 32124
